### ISSUE TITLE
Installation? 

### ISSUE THREAD

**Issue by zilveer** [cmgmyr/test-messenger-laravel55#1]
Hello,
How can I use this with Laravel 5.5?
Is there any known issues?

Regards

**Comment by cmgmyr** [comment]
Hi @zilveer, this is just a testing repo for me and for a basic example how you'd use the package. Please check out the [main repo](https://github.com/cmgmyr/laravel-messenger) for detailed installation instructions.

**Comment by zilveer** [comment]
@cmgmyr thanks for your reply.
Is there any frontend UI for this package?

regards

**Comment by cmgmyr** [comment]
No, not really - I have some [basic examples](https://github.com/cmgmyr/laravel-messenger/tree/master/examples) built in just basic Bootstrap as a starting point. You could certainly expand upon these or create something totally custom...it's really up to you 🙂
